default_duration_limit: 150  # Maximum time difference between newest and oldest message, seconds, overrides -d flag
output-prefix: /media/storage/bags/realsense
# output-prefix: /home/tj2/Diff-Swerve-ROS/tj2_camera/bags
topics:
- /camera/aligned_depth_to_color/camera_info
- /camera/aligned_depth_to_color/image_raw
- /camera/depth/camera_info
- /camera/depth/image_rect_raw
- /camera/infra/camera_info
- /camera/infra/image_raw
- /camera/color/camera_info
- /camera/color/image_raw

- /camera/accel/imu_info
- /camera/accel/sample
- /camera/gyro/imu_info
- /camera/gyro/sample
- /tj2/odom

- /laser/scan
- /tj2/imu
