### Common costmap parameters ###
robot_radius: 0.0
footprint_padding: 0.0

# without bumper:
# footprint: [[-0.23, -0.23], [-0.23, 0.23], [0.23, 0.23], [0.23, -0.23]]

# with bumper:
# footprint: [[-0.313, -0.313], [-0.313, 0.313], [0.313, 0.313], [0.313, -0.313]]
footprint: [[-0.27, -0.27], [-0.27, 0.27], [0.27, 0.27], [0.27, -0.27]]

inflation:
    enabled: true
    cost_scaling_factor: 3.0
    inflation_radius: 0.5

# obstacle_range: 2.0
# raytrace_range: 4.0

transform_tolerance: 0.075  # 0.2
