update_interval: 0.01

base_frame: "base_link"
odom_frame: "odom"
map_frame: "map"
imu_frame: "imu"

cmd_vel_timeout: 0.5
min_linear_cmd: 0.05
min_angular_z_cmd: 0.1
zero_epsilon: 0.001

pose_estimate_x_std: 0.05
pose_estimate_y_std: 0.05
pose_estimate_theta_std_deg: 3.0

odom_covariance: [
  5e-2, 0.0, 0.0, 0.0, 0.0, 0.0,
  0.0, 5e-2, 0.0, 0.0, 0.0, 0.0,
  0.0, 0.0, 5e-2, 0.0, 0.0, 0.0,
  0.0, 0.0, 0.0, 5e-2, 0.0, 0.0,
  0.0, 0.0, 0.0, 0.0, 5e-2, 0.0,
  0.0, 0.0, 0.0, 0.0, 0.0, 5e-2
]
twist_covariance: [
  10e-2, 0.0, 0.0, 0.0, 0.0, 0.0,
  0.0, 10e-2, 0.0, 0.0, 0.0, 0.0,
  0.0, 0.0, 10e-2, 0.0, 0.0, 0.0,
  0.0, 0.0, 0.0, 10e-2, 0.0, 0.0,
  0.0, 0.0, 0.0, 0.0, 10e-2, 0.0,
  0.0, 0.0, 0.0, 0.0, 0.0, 10e-2
]
imu_orientation_covariance: [
  10e-2, 0.0, 0.0,
  0.0, 10e-2, 0.0,
  0.0, 0.0, 10e-2
]
imu_angular_velocity_covariance: [
  10e-2, 0.0, 0.0,
  0.0, 10e-2, 0.0,
  0.0, 0.0, 10e-2
]
imu_linear_acceleration_covariance: [
  100e-2, 0.0, 0.0,
  0.0, 100e-2, 0.0,
  0.0, 0.0, 100e-2
]