watch_topics:
  - /camera/color/camera_info
  - /camera/depth/camera_info
  - /laser/scan
  - /limelight/color/camera_info
  - /tj2/is_autonomous
  - /tj2/match_time
  - /tj2/odom
  - /tj2/joint_states
  - /tj2/powercell/detections
  - /tj2/team_color
  - /tj2/waypoint_markers
watch_nodes:
  - /base_footprint_to_camera
  - /base_footprint_to_imu
  - /base_footprint_to_laser
  - /base_footprint_to_limelight
  - /camera/camera_post_processing_manager
  - /camera/points_xyzrgb_sw_registered
  - /camera/realsense2_camera
  - /camera/realsense2_camera_manager
  - /joint_state_publisher
  - /laser/laser_filter
  - /laser/rplidarNode
  - /move_base
  - /pursuit/pursuit_move_base
  - /robot_state_publisher
  - /rosbag_controlled_recording
  - /tj2/tj2_description
  - /tj2/tj2_match_watcher
  - /tj2/tj2_networktables
  - /tj2/tj2_pursuit
  - /tj2/tj2_riolog
  - /tj2/tj2_tunnel
  - /tj2/tj2_waypoints
  - /tj2/tj2_yolo
  - /tj2_camera_watcher
  - /tj2_laser_slam
  - /twist_mux
